[package]
name = "cc4rs"
version = "0.1.0"
edition = "2024"
description = "Creative Coding framework for Rust, using Sokol framework"
license = "MPL-2.0"
repository = "https://github.com/cc4v/cc4rs"

[dependencies]
# sokol = { version="*", git="https://github.com/floooh/sokol-rust.git" }
sokol = { path = "./externals/sokol-rust", version = "0.1" }
stack-stack = "0.1.0"
image = "0.25"
